### ISSUE TITLE
Instgram - FaceBook

### ISSUE THREAD

**Issue by 3mk454if** [IntelCoreI6/gmail-suffix-generator#2]
Hi the emails are working fine with every platform but I can't make more than 1 account on Instagram - Facebook
I appreciate your efforts but can you fix this problem?

**Comment by IntelCoreI6** [comment]
Yeah, this is a known problem Instagram and most other meta products prohibit these types of emails to prevent people from mass-creating accounts.  This is not a problem with the program, some sites just prevent you from using these emails.
