### ISSUE TITLE
what is the passwords to these?

### ISSUE THREAD

**Issue by Zeerunsyou** [IntelCoreI6/gmail-suffix-generator#6]

**Comment by IntelCoreI6** [comment]
Hey there

Let me clarify the purpose of this script. The script is not intended to create Gmail accounts nor does it provide passwords for any accounts.

Instead, the script generates email addresses with suffixes that can be used for various purposes such as mass creating accounts on other services. These suffixes are simply modifiers added to an **existing Gmail address** using the plus sign (+).

For instance, if your Gmail address is "[example@gmail.com](mailto:example@gmail.com)," the script can generate addresses like "[example+suffix1@gmail.com](mailto:example+suffix1@gmail.com)," "[example+suffix2@gmail.come](mailto:example+suffix2@gmail.come)". 

These addresses are seen as separate mail addresses by other services, but all emails sent to these addresses will still land in the same inbox of your primary Gmail account. You can still see to which address the mail is send.

Like this:
![image](https://github.com/IntelCoreI6/gmail-suffix-generator/assets/63975399/69fe6396-7505-48fb-9c35-8fa9058a560f)

These generated addresses can then be used for tasks like creating accounts on different websites or services, but it's important to note that the script itself doesn't handle any account creation processes or provide passwords.

If you have any further questions or need clarification on how to use the script, feel free to ask.

Best regards

https://github.com/IntelCoreI6/gmail-suffix-generator/issues/6
